const Icons = {
    eye:require('./eye.png'),
    eyeClose:require('./eye_close.png'),
    completed:require('./completed.png'),
    back:require('./back.png'),
    mobile:require('./mobile.png'),
    model:require('./model_3d.png'),
    web:require('./web_design.png'),
    illustration:require('./illustration.png'),
    drawing:require('./drawing.png'),
    animation:require('./animation.png'),
    education:require('./education.png'),
    network:require('./networking.png'),
    coding:require('./coding.png'),
    notification:require('./notification.png'),
    play:require('./play_1.png'),
    time:require('./time.png'),
    star:require('./star.png'),
    search:require('./search.png'),
    profile:require('./profile.png'),
    email:require('./email.png'),
    password:require('./password.png'),
    call:require('./call.png'),
    star1:require('./star_1.png'),
    new:require('./new.png'),
    reminder:require('./reminder.png'),
    home:require('./home.png'),
    sun:require('./sun.png'),
    rightArrow:require('./right_arrow.png'),
    filter:require('./filter.png'),
    menu:require('./menu.png'),
    comment:require('./comment.png'),
    heart:require('./heart.png'),
    reply:require('./reply.png'),
    send:require('./send.png'),
    share:require('./share.png'),
    check:require('./checked.png'),
    all:require('./all.png'),
    staff:require('./staff_pick.png'),
    original:require('./original.png'),
    checkoff:require('./checkbox_off.png'),
    checkon:require('./checkbox_on.png'),
    heartoff:require('./heart_off.png'),
    fb:require('./facebook.png'),
    google:require('./google.png'),
    download:require('./download.png'),
    lock:require('./lock.png'),
    camera:require('./camera.png')


}

export default Icons