
export const Strings={
    Login:'Login',
    Register:'Register',
    userormail:'Username or Email',
    pass:'Password',
    orlgnwith:'or login with',
    newuser:'New User?',
    signupnow:' Sign Up Now',
    username:'Username',
    email:'Email',
    createAccount:'CREATE ACCOUNT',
    already:'Already a User?',
    orsignup:'or sign up with',
    chooseCategory:'Choose Categories',
    continue:'CONTINUE',
    helloProg:'Hello, Peter!',
    date:'Tuesday, 9th Feb 2022',
    howto:'HOW TO',
    makeur:'Make your brand more visible with our checklist',
    byscoot:'By Scott Haris',
    startear:'Start Learning',
    category:'Categories',
    popularcourse:'Popular Courses',
    seeall:'See All',
    searchFortopic:'Search for Topics, Courses & Education',
    topsearches:'Top Searches',
    browseCat:'Browse Categories',
    profile:'Profile',
    byprog:'ByProgrammers',
    fullstack:'Full Stack Developer',
    overall:'Overall Progress',
    becomeMember:'+ Become Member',
    mobiledesign:'Mobile Design',
    result:'5,761 Results',
    students:'Students',
    file:"Files",
    lorem:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis nunc eget ante euismod viverra ut condimentum erat. ',
    reply:'Reply',
    like:'Like',
    typesome:'Type Something',
    follow:'Follow',
    about:'About Me',
    showMore:'Show More',
    mycourse:'My Courses (4)',
    studentrating:'Student Rating',
    studentSatisfy:'Students satisfied with courses',
    verysatisy:'Very Satisfied',
    satisy:'Safisfied',
    netural:'Neutral',
    poor:'Poor',
    studentReview:"Student Reviews",
    connectHere:'Connect Here',
    member:"Membership",
    unlimitedStudy:"Unlimited Study \nAnytime, Anywhere",
    choseplan:"Choose a plan",
    startTrail:"Start Free Trail",
    notification:"Notifications",
    today:"Today",
    ExploreOnline:"Explore Online \nCourses",
    allType:"All type of educational & Professional courses \navailable online",
    next:'Next',
    filter:"Filter",
    cancel:'Cancel',
    classType:"Class Type",
    classLevel:'Class Level',
    created:'Created Within',
    reset:'Reset',
    apply:'Apply',
    theultimate:"The Ultimate Ui/Ux Course \nBeginner to Advanced",
    google:'Google',
    fb:'Facebook'

}